In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import scipy.stats as sts
import numpy as np

In [4]:
speciesfile = "data/20200929spcs_edit.csv"

# Read our Kickstarter data into pandas
spc_DB = pd.read_csv(speciesfile)
spc_DB.count()

Scientific Name         1897
Common Name             1897
Threatened status       1897
ACT                     1897
NSW                     1897
NT                      1897
QLD                     1897
SA                      1897
TAS                     1897
VIC                     1897
WA                      1897
ACI                     1897
CKI                     1897
CI                      1897
CSI                     1897
JBT                     1897
NFI                     1897
HMI                     1897
AAT                     1897
CMA                     1897
Listed SPRAT TaxonID    1897
Kingdom                 1897
Class                   1897
Family                  1897
Genus                   1897
Species                 1897
dtype: int64

In [7]:
spc_DB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1897 entries, 0 to 1896
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Scientific Name       1897 non-null   object
 1   Common Name           1897 non-null   object
 2   Threatened status     1897 non-null   object
 3   ACT                   1897 non-null   object
 4   NSW                   1897 non-null   object
 5   NT                    1897 non-null   object
 6   QLD                   1897 non-null   object
 7   SA                    1897 non-null   object
 8   TAS                   1897 non-null   object
 9   VIC                   1897 non-null   object
 10  WA                    1897 non-null   object
 11  ACI                   1897 non-null   object
 12  CKI                   1897 non-null   object
 13  CI                    1897 non-null   object
 14  CSI                   1897 non-null   object
 15  JBT                   1897 non-null   object
 16  NFI                   1897 non-null   object
 17  HMI                   1897 non-null   object
 18  AAT                   1897 non-null   object
 19  CMA                   1897 non-null   object
 20  Listed SPRAT TaxonID  1897 non-null   int64
 21  Kingdom               1897 non-null   object
 22  Class                 1897 non-null   object
 23  Family                1897 non-null   object
 24  Genus                 1897 non-null   object
 25  Species               1897 non-null   object
dtypes: int64(1), object(25)
memory usage: 385.5+ KB

In [9]:
spc_DB.columns

Index(['Scientific Name', 'Common Name', 'Threatened status', 'ACT', 'NSW',
       'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA', 'ACI', 'CKI', 'CI', 'CSI', 'JBT',
       'NFI', 'HMI', 'AAT', 'CMA', 'Listed SPRAT TaxonID', 'Kingdom', 'Class',
       'Family', 'Genus', 'Species'],
      dtype='object')

In [10]:
spc_DB_1 = spc_DB.loc[:, ["Scientific Name", "Common Name", "Threatened status",
                                    "ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA", 'Kingdom', 'Class',
       'Family', 'Genus', 'Species']]

In [11]:

spc_DB_1

,Scientific Name,Common Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,Kingdom,Class,Family,Genus,Species
0,Neophoca cinerea,"Australian SeaNalion, Australian Sea Lion",Vulnerable,Na,Na,Na,Na,Yes,Na,Na,Yes,Animalia,Mammalia,Otariidae,Neophoca,cinerea
1,Mirounga leonina,Southern Elephant Seal,Vulnerable,Na,Na,Na,Na,Yes,Yes,Na,Na,Animalia,Mammalia,Phocidae,Mirounga,leonina
2,Balaenoptera borealis,Sei Whale,Vulnerable,Na,Yes,Na,Yes,Yes,Yes,Yes,Yes,Animalia,Mammalia,Balaenopteridae,Balaenoptera,borealis
3,Balaenoptera musculus,Blue Whale,Endangered,Na,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Animalia,Mammalia,Balaenopteridae,Balaenoptera,musculus
4,Balaenoptera physalus,Fin Whale,Vulnerable,Na,Yes,Na,Yes,Yes,Yes,Yes,Yes,Animalia,Mammalia,Balaenopteridae,Balaenoptera,physalus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1892,Ammoniropa vigens,Ammonite Pinwheel Snail,Critically Endangered,Na,Na,Na,Na,Na,Yes,Na,Na,Animalia,Gastropoda,Charopidae,Ammoniropa,vigens
1893,Carinascincus palfreymani,"Pedra Branca Skink, Pedra Branca CoolNaskink,...",Vulnerable,Na,Na,Na,Na,Na,Yes,Na,Na,Animalia,Reptilia,Scincidae,Carinascincus,palfreymani
1894,Thinornis cucullatus cucullatus,"Hooded Plover (eastern), Eastern Hooded Plover",Vulnerable,Na,Yes,Na,Na,Yes,Yes,Yes,Na,Animalia,Aves,Charadriidae,Thinornis,cucullatus
1895,Petrogale lateralis kimberleyensis,"Wiliji, West Kimberley RockNawallaby",Vulnerable,Na,Na,Na,Na,Na,Na,Na,Yes,Animalia,Mammalia,Macropodidae,Petrogale,lateralis
1896,Leucopatus anophthalmus,Blind Velvet Worm,Endangered,Na,Na,Na,Na,Na,Yes,Na,Na,Animalia,Onychophora (no class),Peripatopsidae,Leucopatus,anophthalmus

In [22]:
spc_DB_2 = spc_DB_1[spc_DB_1["Scientific Name"] != "Na"]
spc_DB_3 = spc_DB_2[spc_DB_1["Common Name"] != "Na"]
spc_DB_4 = spc_DB_3[spc_DB_1["Threatened status"] != "Na"]
spc_DB_5 = spc_DB_4[spc_DB_1["Kingdom"] != "Na"]
spc_DB_6 = spc_DB_5[spc_DB_1["Class"] != "Na"]
spc_DB_7 = spc_DB_6[spc_DB_1["Family"] != "Na"]
spc_DB_8 = spc_DB_7[spc_DB_1["Genus"] != "Na"]
spc_DB_9 = spc_DB_8[spc_DB_1["Species"] != "Na"]
spc_DB_9

C:\Users\amyel\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\amyel\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.
C:\Users\amyel\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """
C:\Users\amyel\anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

C:\Users\amyel\anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  import sys
C:\Users\amyel\anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,Scientific Name,Common Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,Kingdom,Class,Family,Genus,Species
0,Neophoca cinerea,"Australian SeaNalion, Australian Sea Lion",Vulnerable,Na,Na,Na,Na,Yes,Na,Na,Yes,Animalia,Mammalia,Otariidae,Neophoca,cinerea
1,Mirounga leonina,Southern Elephant Seal,Vulnerable,Na,Na,Na,Na,Yes,Yes,Na,Na,Animalia,Mammalia,Phocidae,Mirounga,leonina
2,Balaenoptera borealis,Sei Whale,Vulnerable,Na,Yes,Na,Yes,Yes,Yes,Yes,Yes,Animalia,Mammalia,Balaenopteridae,Balaenoptera,borealis
3,Balaenoptera musculus,Blue Whale,Endangered,Na,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Animalia,Mammalia,Balaenopteridae,Balaenoptera,musculus
4,Balaenoptera physalus,Fin Whale,Vulnerable,Na,Yes,Na,Yes,Yes,Yes,Yes,Yes,Animalia,Mammalia,Balaenopteridae,Balaenoptera,physalus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1892,Ammoniropa vigens,Ammonite Pinwheel Snail,Critically Endangered,Na,Na,Na,Na,Na,Yes,Na,Na,Animalia,Gastropoda,Charopidae,Ammoniropa,vigens
1893,Carinascincus palfreymani,"Pedra Branca Skink, Pedra Branca CoolNaskink,...",Vulnerable,Na,Na,Na,Na,Na,Yes,Na,Na,Animalia,Reptilia,Scincidae,Carinascincus,palfreymani
1894,Thinornis cucullatus cucullatus,"Hooded Plover (eastern), Eastern Hooded Plover",Vulnerable,Na,Yes,Na,Na,Yes,Yes,Yes,Na,Animalia,Aves,Charadriidae,Thinornis,cucullatus
1895,Petrogale lateralis kimberleyensis,"Wiliji, West Kimberley RockNawallaby",Vulnerable,Na,Na,Na,Na,Na,Na,Na,Yes,Animalia,Mammalia,Macropodidae,Petrogale,lateralis
1896,Leucopatus anophthalmus,Blind Velvet Worm,Endangered,Na,Na,Na,Na,Na,Yes,Na,Na,Animalia,Onychophora (no class),Peripatopsidae,Leucopatus,anophthalmus

In [26]:
spc_DB_9["Kingdom"].unique()

array(['Animalia', 'Plantae'], dtype=object)

In [28]:
spc_DB_9["Class"].unique()

array(['Mammalia', 'Aves', 'Reptilia', 'Amphibia', 'Magnoliopsida',
       'Liliopsida', 'Polypodiatae', 'Cycadatae', 'Lycopodopiatae',
       'Insecta', 'Actinopterygii', 'Pinatae', 'Chondrichthyes',
       'Malacostraca', 'Oligochaeta', 'Streptophyta (no class)',
       'Psilotatae', 'Bryopsida', 'Asteroidea', 'Gastropoda', 'Arachnida',
       'Rhodophyceae', 'Sarcopterygii', 'Bivalvia', 'Remipedia',
       'Onychophora (no class)'], dtype=object)

In [29]:
spc_DB_9["Family"].unique()

array(['Otariidae', 'Phocidae', 'Balaenopteridae', 'Balaenidae',
       'Muridae', 'Megadermatidae', 'Hipposideridae', 'Vespertilionidae',
       'Pteropodidae', 'Potoroidae', 'Vombatidae', 'Macropodidae',
       'Petauridae', 'Burramyidae', 'Peramelidae', 'Thylacomyidae',
       'Dasyuridae', 'Myrmecobiidae', 'Thylacinidae', 'Estrildidae',
       'Pardalotidae', 'Meliphagidae', 'Maluridae', 'Pachycephalidae',
       'Petroicidae', 'Atrichornithidae', 'Apodidae', 'Psittacidae',
       'Cacatuidae', 'Scolopacidae', 'Charadriidae', 'Pedionomidae',
       'Turnicidae', 'Falconidae', 'Megapodiidae', 'Accipitridae',
       'Ardeidae', 'Fregatidae', 'Procellariidae', 'Diomedeidae',
       'Hydrophiidae', 'Elapidae', 'Typhlopidae', 'Scincidae', 'Agamidae',
       'Pygopodidae', 'Gekkonidae', 'Chelidae', 'Cheloniidae',
       'Dermochelyidae', 'Microhylidae', 'Hylidae', 'Myobatrachidae',
       'Limnodynastidae', 'Rubiaceae', 'Rhamnaceae', 'Euphorbiaceae',
       'Asteraceae', 'Orchidaceae', 'Dennstaedtiaceae', 'Myoporaceae',
       'Myrtaceae', 'Poaceae', 'Cyperaceae', 'Lamiaceae', 'Fabaceae',
       'Apocynaceae', 'Violaceae', 'Sterculiaceae', 'Tremandraceae',
       'Proteaceae', 'Sapindaceae', 'Pittosporaceae', 'Zamiaceae',
       'Haemodoraceae', 'Rutaceae', 'Scrophulariaceae', 'Amaranthaceae',
       'Aspleniaceae', 'Ranunculaceae', 'Stylidiaceae', 'Verbenaceae',
       'Santalaceae', 'Cycadaceae', 'Polygonaceae', 'Frankeniaceae',
       'Onagraceae', 'Arecaceae', 'Haloragaceae', 'Musaceae',
       'Eriocaulaceae', 'Dasypogonaceae', 'Solanaceae',
       'Xanthorrhoeaceae', 'Chenopodiaceae', 'Gyrostemonaceae',
       'Acanthaceae', 'Pandanaceae', 'Elaeocarpaceae', 'Polygalaceae',
       'Brassicaceae', 'Apiaceae', 'Surianaceae', 'Epacridaceae',
       'Araliaceae', 'Liliaceae', 'Olacaceae', 'Gentianaceae',
       'Meliaceae', 'Goodeniaceae', 'Lauraceae', 'Centrolepidaceae',
       'Loganiaceae', 'Tiliaceae', 'Oleaceae', 'Hymenophyllaceae',
       'Dilleniaceae', 'Marattiaceae', 'Casuarinaceae', 'Boryaceae',
       'Sapotaceae', 'Plantaginaceae', 'Stackhousiaceae', 'Celastraceae',
       'Dryopteridaceae', 'Ebenaceae', 'Symplocaceae', 'Corynocarpaceae',
       'Thymelaeaceae', 'Moraceae', 'Winteraceae', 'Caryophyllaceae',
       'Lycopodiaceae', 'Pteridaceae', 'Castniidae', 'Eustheniidae',
       'Sturnidae', 'Zosteropidae', 'Alcedinidae', 'Anatidae',
       'Campephagidae', 'Casuariidae', 'Columbidae', 'Artamidae',
       'Laridae', 'Muscicapidae', 'Phaethontidae', 'Ploceidae',
       'Strigidae', 'Tytonidae', 'Galaxiidae', 'Percichthyidae',
       'Retropinnidae', 'Pseudomugilidae', 'Dromaiidae',
       'Melanotaeniidae', 'Nymphalidae', 'Lycaenidae', 'Malvaceae',
       'Simaroubaceae', 'Urticaceae', 'Cucurbitaceae', 'Podocarpaceae',
       'Hydatellaceae', 'Asclepiadaceae', 'Atherinidae', 'Sulidae',
       'Acanthizidae', 'Pristidae', 'Araceae', 'Parastacidae',
       'Brachionichthyidae', 'Megascolecidae', 'Hydrobatidae',
       'Passeridae', 'Psophodidae', 'Lamnidae', 'Characeae',
       'Araucariaceae', 'Gobiidae', 'Cupressaceae', 'Restionaceae',
       'Phormiaceae', 'Molluginaceae', 'Xyridaceae', 'Agavaceae',
       'Blechnaceae', 'Icacinaceae', 'Loranthaceae', 'Psilotaceae',
       'Lepidoziaceae', 'Rallidae', 'Eleotridae', 'Synbranchidae',
       'Rhincodontidae', 'Nannopercidae', 'Boidae', 'Colletidae',
       'Phasmatidae', 'Lucanidae', 'Poraniidae', 'Bulimulidae',
       'Camaenidae', 'Idiopidae', 'Emballonuridae', 'Phalacrocoracidae',
       'Cunoniaceae', 'Monimiaceae', 'Delesseriaceae', 'Ceratodontidae',
       'Selaginellaceae', 'Squalidae', 'Serranidae', 'Triakidae',
       'Trachichthyidae', 'Carcharhinidae', 'Thelypteridaceae',
       'Centrolophidae', 'Scombridae', 'Terapontidae', 'Gempylidae',
       'Rostratulidae', 'Hesperiidae', 'Alaudidae', 'Charopidae',
       'Helicarionidae', 'Aponogetonaceae', 'Annonaceae',
       'Rhaphidophoridae', 'Rhinonycteridae', 'Hyriidae',
       'Diplodactylidae', 'Rajidae', 'Primulaceae', 'Iridaceae',
       'Geraniaceae', 'Oecophoridae', 'Menyanthaceae', 'Phascolarctidae',
       'Sphyrnidae', 'Asterinidae', 'Noctuidae', 'Plumbaginaceae',
       'Soricidae', 'Pseudococcidae', 'Kumongidae', 'Ericaceae',
       'Tachyglossidae', 'Rhinolophidae', 'Miniopteridae', 'Triozidae',
       'Rhizophoraceae', 'Migidae', 'Peripatopsidae'], dtype=object)

In [30]:
spc_DB_9.to_csv("data/spcs_cleaned.csv")