In [5]:
import pandas as pd 
import matplotlib.pyplot as plt
import scipy.stats as sts
import numpy as np

In [28]:
speciesfile = "../data/species_cleaned.csv"

# Read our Kickstarter data into pandas
species_DB = pd.read_csv(speciesfile)
species_DB.head()
species_DB.groupby("Kingdom").count()

,Unnamed: 0,Species,Common_Name,Category,Presence_Type,Location,Phylum,Class,Order,Family
Kingdom,,,,,,,,,,
Animalia,548,548,548,548,548,548,548,548,548,548
Plantae,1408,1408,1102,1408,1408,1408,1408,1408,1408,1408

In [12]:
plants = species_DB[species_DB["Kingdom"] == "Plantae"]
plants

,Unnamed: 0,Species,Common_Name,Category,Presence_Type,Location,Kingdom,Phylum,Class,Order,Family
0,0,Abutilon julianae,Norfolk Island Abutilon,Critically Endangered,Endemic,"AET, NI",Plantae,Magnoliophyta,Magnoliopsida,Malvales,Malvaceae
1,1,Acacia ammophila,NaN,Vulnerable,Endemic,QLD,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
2,2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",Vulnerable,Endemic,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
3,3,Acacia aphylla,Leafless Rock Wattle,Vulnerable,Endemic,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
4,4,Acacia aprica,Blunt Wattle,Endangered,Endemic,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
...,...,...,...,...,...,...,...,...,...,...,...
1945,1945,Zieria parrisiae,Parris's Zieria,Critically Endangered,Endemic,NSW,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae
1946,1946,Zieria prostrata,Headland Zieria,Endangered,Endemic,NSW,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae
1947,1947,Zieria rimulosa,NaN,Vulnerable,Endemic,QLD,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae
1948,1948,Zieria tuberculata,Warty Zieria,Vulnerable,Endemic,NSW,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae
1949,1949,Zieria verrucosa,NaN,Vulnerable,Endemic,QLD,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae

In [18]:
plants_CE = plants[plants["Category"] == "Critically Endangered"]

In [19]:
plants_CE

,Unnamed: 0,Species,Common_Name,Category,Presence_Type,Location,Kingdom,Phylum,Class,Order,Family
0,0,Abutilon julianae,Norfolk Island Abutilon,Critically Endangered,Endemic,"AET, NI",Plantae,Magnoliophyta,Magnoliopsida,Malvales,Malvaceae
18,18,Acacia cochlocarpa subsp. velutinosa,Velvety Spiral Pod Wattle,Critically Endangered,Endemic,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
24,24,Acacia dangarensis,NaN,Critically Endangered,Present,NSW,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
29,29,Acacia equisetifolia,a shrub,Critically Endangered,Endemic,NT,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
45,45,Acacia leptoneura,NaN,Critically Endangered,Present,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
...,...,...,...,...,...,...,...,...,...,...,...
1907,1907,Wikstroemia australis,Kurrajong,Critically Endangered,Endemic,"AET, NI",Plantae,Magnoliophyta,Magnoliopsida,Myrtales,Thymelaeaceae
1908,1908,Wollemia nobilis,Wollemi Pine,Critically Endangered,Endemic,NSW,Plantae,Pinophyta,Pinatae,Pinales,Araucariaceae
1931,1931,Zieria buxijugum,Box Range Zieria,Critically Endangered,Endemic,NSW,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae
1944,1944,Zieria odorifera subsp. warrabahensis,NaN,Critically Endangered,Endemic,NSW,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae
1945,1945,Zieria parrisiae,Parris's Zieria,Critically Endangered,Endemic,NSW,Plantae,Magnoliophyta,Magnoliopsida,Sapindales,Rutaceae

In [25]:
plants.groupby("Category").count()

,Unnamed: 0,Species,Common_Name,Presence_Type,Location,Kingdom,Phylum,Class,Order,Family
Category,,,,,,,,,,
Critically Endangered,196,196,157,196,196,196,196,196,196,196
Endangered,566,566,468,566,566,566,566,566,566,566
Extinct,38,38,20,38,38,38,38,38,38,38
Vulnerable,608,608,457,608,608,608,608,608,608,608

In [29]:
animals = species_DB[species_DB["Kingdom"] == "Animalia"]

In [31]:
animals.groupby("Category").count()

,Unnamed: 0,Species,Common_Name,Presence_Type,Location,Kingdom,Phylum,Class,Order,Family
Category,,,,,,,,,,
Conservation Dependent,8,8,8,8,8,8,8,8,8,8
Critically Endangered,91,91,91,91,91,91,91,91,91,91
Endangered,179,179,179,179,179,179,179,179,179,179
Extinct,53,53,53,53,53,53,53,53,53,53
Extinct in the wild,1,1,1,1,1,1,1,1,1,1
Vulnerable,216,216,216,216,216,216,216,216,216,216

species_cleaned.to_csv("data/species_cleaned.csv")