In [5]:
import pandas as pd 
import matplotlib.pyplot as plt
import scipy.stats as sts
import numpy as np

In [6]:
speciesfile = "data/species.csv"

# Read our Kickstarter data into pandas
species_DB = pd.read_csv(speciesfile)
species_DB.count()

FileNotFoundError: [Errno 2] File data/species.csv does not exist: 'data/species.csv'

In [3]:
species_DB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1956 entries, 0 to 1955
Data columns (total 12 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Species                                                                   1956 non-null   object
 1   Common Name                                                               1650 non-null   object
 2   Category                                                                  1956 non-null   object
 3   Type of Presence                                                          1956 non-null   object
 4   Comments                                                                  74 non-null     object
 5   Location(s)                                                               1956 non-null   object
 6   Kingdom                                                                   1956 non-null   object
 7   Phylum                                                                    1956 non-null   object
 8   Class                                                                     1956 non-null   object
 9   Order                                                                     1956 non-null   object
 10  Family                                                                    1956 non-null   object
 11  EPBC Act Threatened Species in Australia (Generated 2020-09-29 22:36:16)  0 non-null      float64
dtypes: float64(1), object(11)
memory usage: 183.5+ KB

In [4]:
species_DB.columns

Index(['Species', 'Common Name', 'Category', 'Type of Presence', 'Comments',
       'Location(s)', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family',
       'EPBC Act Threatened Species in Australia (Generated 2020-09-29 22:36:16)'],
      dtype='object')

In [6]:
species_DB

,Species,Common Name,Category,Type of Presence,Comments,Location(s),Kingdom,Phylum,Class,Order,Family,EPBC Act Threatened Species in Australia (Generated 2020-09-29 22:36:16)
0,Abutilon julianae,Norfolk Island Abutilon,Critically Endangered,Endemic,Norfolk Island,"AET, NI",Plantae,Magnoliophyta,Magnoliopsida,Malvales,Malvaceae,NaN
1,Acacia ammophila,NaN,Vulnerable,Endemic,NaN,QLD,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",Vulnerable,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
3,Acacia aphylla,Leafless Rock Wattle,Vulnerable,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
4,Acacia aprica,Blunt Wattle,Endangered,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1951,Zosterops albogularis,"White-chested White-eye, Norfolk Island Silvereye",Extinct,Extinct,Norfolk Island,"AET, NI",Animalia,Chordata,Aves,Passeriformes,Zosteropidae,NaN
1952,Zosterops strenuus,Robust White-eye,Extinct,Extinct,Lord Howe Island,NSW,Animalia,Chordata,Aves,Passeriformes,Zosteropidae,NaN
1953,Zyzomys maini,"Arnhem Rock-rat, Arnhem Land Rock-rat, Kodjperr",Vulnerable,Endemic,NaN,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN
1954,Zyzomys palatalis,"Carpentarian Rock-rat, Aywalirroomoo",Endangered,Endemic,NaN,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN
1955,Zyzomys pedunculatus,"Central Rock-rat, Antina",Critically Endangered,Present,NaN,"NT, WA",Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN

In [3]:
species_DB.columns

NameError: name 'species_DB' is not defined

In [11]:
species_DB2 = species_DB[species_DB["Species"] != "Na"]
species_DB3 = species_DB2[species_DB2["Common Name"] != "Na"]
species_DB4 = species_DB3[species_DB3["Category"] != "Na"]
species_DB5 = species_DB4[species_DB4["Kingdom"] != "Na"]
species_DB6 = species_DB5[species_DB5["Class"] != "Na"]
species_DB7 = species_DB6[species_DB6["Family"] != "Na"]
species_DB8 = species_DB7[species_DB7["Order"] != "Na"]
species_DB9 = species_DB8[species_DB8["Phylum"] != "Na"]
species_DB10 = species_DB9[species_DB9["Type of Presence"] != "Na"]
species_DB10

,Species,Common Name,Category,Type of Presence,Comments,Location(s),Kingdom,Phylum,Class,Order,Family,EPBC Act Threatened Species in Australia (Generated 2020-09-29 22:36:16)
0,Abutilon julianae,Norfolk Island Abutilon,Critically Endangered,Endemic,Norfolk Island,"AET, NI",Plantae,Magnoliophyta,Magnoliopsida,Malvales,Malvaceae,NaN
1,Acacia ammophila,NaN,Vulnerable,Endemic,NaN,QLD,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",Vulnerable,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
3,Acacia aphylla,Leafless Rock Wattle,Vulnerable,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
4,Acacia aprica,Blunt Wattle,Endangered,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1951,Zosterops albogularis,"White-chested White-eye, Norfolk Island Silvereye",Extinct,Extinct,Norfolk Island,"AET, NI",Animalia,Chordata,Aves,Passeriformes,Zosteropidae,NaN
1952,Zosterops strenuus,Robust White-eye,Extinct,Extinct,Lord Howe Island,NSW,Animalia,Chordata,Aves,Passeriformes,Zosteropidae,NaN
1953,Zyzomys maini,"Arnhem Rock-rat, Arnhem Land Rock-rat, Kodjperr",Vulnerable,Endemic,NaN,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN
1954,Zyzomys palatalis,"Carpentarian Rock-rat, Aywalirroomoo",Endangered,Endemic,NaN,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN
1955,Zyzomys pedunculatus,"Central Rock-rat, Antina",Critically Endangered,Present,NaN,"NT, WA",Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN

In [13]:
#'Species', 'Common Name', 'Category', 'Type of Presence',
#'Location(s)', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family',


species_DB10["Category"].unique()

array(['Critically Endangered', 'Vulnerable', 'Endangered', 'Extinct',
       'Conservation Dependent', 'Extinct in the wild'], dtype=object)

In [16]:
species_DB10 = species_DB10.rename(columns = {'Type of Presence': 'Presence_Type','Common Name': 'Common_Name', 'Location(s)': 'Location'}, inplace = False)

In [17]:
species_DB10

,Species,Common_Name,Category,Presence_Type,Comments,Location,Kingdom,Phylum,Class,Order,Family,EPBC Act Threatened Species in Australia (Generated 2020-09-29 22:36:16)
0,Abutilon julianae,Norfolk Island Abutilon,Critically Endangered,Endemic,Norfolk Island,"AET, NI",Plantae,Magnoliophyta,Magnoliopsida,Malvales,Malvaceae,NaN
1,Acacia ammophila,NaN,Vulnerable,Endemic,NaN,QLD,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",Vulnerable,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
3,Acacia aphylla,Leafless Rock Wattle,Vulnerable,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
4,Acacia aprica,Blunt Wattle,Endangered,Endemic,NaN,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1951,Zosterops albogularis,"White-chested White-eye, Norfolk Island Silvereye",Extinct,Extinct,Norfolk Island,"AET, NI",Animalia,Chordata,Aves,Passeriformes,Zosteropidae,NaN
1952,Zosterops strenuus,Robust White-eye,Extinct,Extinct,Lord Howe Island,NSW,Animalia,Chordata,Aves,Passeriformes,Zosteropidae,NaN
1953,Zyzomys maini,"Arnhem Rock-rat, Arnhem Land Rock-rat, Kodjperr",Vulnerable,Endemic,NaN,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN
1954,Zyzomys palatalis,"Carpentarian Rock-rat, Aywalirroomoo",Endangered,Endemic,NaN,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN
1955,Zyzomys pedunculatus,"Central Rock-rat, Antina",Critically Endangered,Present,NaN,"NT, WA",Animalia,Chordata,Mammalia,Rodentia,Muridae,NaN

In [18]:
species_cleaned = species_DB10.loc[:, ["Species", "Common_Name", "Category",
                                    "Presence_Type", "Location",  'Kingdom', "Phylum", 'Class', "Order", 
       'Family']]

In [19]:
species_cleaned

,Species,Common_Name,Category,Presence_Type,Location,Kingdom,Phylum,Class,Order,Family
0,Abutilon julianae,Norfolk Island Abutilon,Critically Endangered,Endemic,"AET, NI",Plantae,Magnoliophyta,Magnoliopsida,Malvales,Malvaceae
1,Acacia ammophila,NaN,Vulnerable,Endemic,QLD,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",Vulnerable,Endemic,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
3,Acacia aphylla,Leafless Rock Wattle,Vulnerable,Endemic,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
4,Acacia aprica,Blunt Wattle,Endangered,Endemic,WA,Plantae,Magnoliophyta,Magnoliopsida,Fabales,Fabaceae
...,...,...,...,...,...,...,...,...,...,...
1951,Zosterops albogularis,"White-chested White-eye, Norfolk Island Silvereye",Extinct,Extinct,"AET, NI",Animalia,Chordata,Aves,Passeriformes,Zosteropidae
1952,Zosterops strenuus,Robust White-eye,Extinct,Extinct,NSW,Animalia,Chordata,Aves,Passeriformes,Zosteropidae
1953,Zyzomys maini,"Arnhem Rock-rat, Arnhem Land Rock-rat, Kodjperr",Vulnerable,Endemic,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae
1954,Zyzomys palatalis,"Carpentarian Rock-rat, Aywalirroomoo",Endangered,Endemic,NT,Animalia,Chordata,Mammalia,Rodentia,Muridae
1955,Zyzomys pedunculatus,"Central Rock-rat, Antina",Critically Endangered,Present,"NT, WA",Animalia,Chordata,Mammalia,Rodentia,Muridae

species_cleaned.to_csv("data/species_cleaned.csv")

In [2]:
species_cleaned

NameError: name 'species_cleaned' is not defined